name: cs3600-mdp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - networkx
  - scipy
  - ipywidgets
  - jupyter
  - notebook
  - altair
  - nltk
  - pip
  - pip:
    - ipython
    - pygame
    - tqdm